# site_title: La Guia, a General Software Guide
# topnav_title: Bottom Lab > Top Lab

title: Bottom Lab > Top Lab

# remote_theme: tomjoht/documentation-theme-jekyll
remote_theme: just-the-docs/just-the-docs

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
aux_links:
  "LaGuia on GitHub":
    - "//github.com/hheisig51/LaGuia"

description: "A general software guide for the CHS Sigma Lab"

feedback_subject_line: Let me know anything, good or bad!
feedback_email: github@eheisig.com
